name: CommandControl
version: '1.0-SNAPSHOT'
main: dev.philippcmd.commandControl.CommandControl
api-version: '1.21'
authors: [ PhilippCMD ]
description: Simple Tool to temporarily deactivate commands

commands:
  deactivate-command:
    description: Deactivate a command.
    usage: /deactivate-command <command>
    permission: op

  reactivate-command:
    description: Reactivate a command.
    usage: /reactivate-command <command>
    permission: op

  restrict-command:
    description: Restrict a command for players without the bypass permission.
    usage: /restrict-command <command>
    permission: op

  reallow-command:
    description: Reallow a restricted command.
    usage: /reallow-command <command
    permission: op